site_name: Roblox Engine Project
site_description: Development log for my Roblox-compatible game engine
theme:
  name: material
  palette:
    # Light mode
    - scheme: default
      primary: blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight

nav:
  - Home: index.md
  - Dev Log: devlog.md
  - Architecture: architecture.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition